# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 089c4996276a573162f48840a9f9260ff7b324450cd97ee3d9d11485fa01a71eab92807d84652436970e5d2d5ad1f0bc214a0126220273b5512020746bd2da3d

test:
  secret_key_base: ee4c4c6ef11e78bef44bd2be96ba5ff036ef446098162806ff7d4a22ad6abf40ca31cf3d3a4e0a3eeecd977c3662423ac0ba8709d371335691fd47f6e39b93fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
