# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f112800d3c51123260dd8a95749a06468af934c7e78e63c8dedcc4d9f9ec514e546f93dfe0c75c86a2dc7ccb241c1a240552ef9eb0cf4bd03e18ee00152d5ebb

test:
  secret_key_base: 937da56b94cdc648237bcd8136ae21dd2cefa6923c879c8aa9b52905b6543b4b9ff31fde8a39b31aba19c79514ff3d655e85baf83c976a67ff035ede71633660

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
